# Every once and a while, there will be a random event, this skript handles that.
# Random event list:
  # 2x mcMMO XP
  # +$10 payout on jobs
  # Towny War
  # Skip towny upkeep for the day (adds 10$ to everyones town)
  # Random Rankup (Will be done manually)
  # Random amount of money for all (100-10000)
  # I'll probably add more here as I go, lol.

command /randomevent:
  trigger:
    if player has permission "kahppa.randomevent":
      send "YES"
    else:
      send "NO"
